Feat(event) : Create Function For Object
jabardigitalservice/event-management-system pull request #15
Opened 2023-10-26 18:01 UTC by johndy2742

### Changes Made

- add a new module called object
- add database migration script

### Purpose

- add create functionality for Object managament

### How Has This Been Tested

- Postman request test
![image](https://github.com/jabardigitalservice/event-management-system/assets/78816767/b41d0a13-bb81-4056-9156-2c5a809278f1)

### Related Links

https://chat.digitalservice.id/boards/team/nii5pbyw1idwxrxjd8bp56mtkw/bte55h31wfjgp9xgry174ur3mae/vbyyag4aadi8ejgca6gtqzs55gc

Project: Event Management System
Participants: @johndy2742, @iqbal167, @alqinsidev

2023-10-27 02:47 UTC, iqbal167 commented on service/src/app/app.go
> +	return app.newrelicApp
where is the initialization for the new relic application?

2023-10-27 03:35 UTC, iqbal167 commented on service/src/modules/object/repository/object.go
> +	err = r.db.Slave.QueryRowContext(ctx, `INSERT INTO "object" ("name", "address", "description", "banner", "logo", "social_media", "organizer", "status", "created_at", "updated_at")
use exec function please

2023-10-27 03:48 UTC, iqbal167 commented on service/src/migration/script/20231024064336_create_table_object.down.sql
add new line

2023-10-27 04:09 UTC, alqinsidev commented on service/src/modules/object/usecase/usecase.go
> +		CreateObject(ctx context.Context, obj entity.Object) (entity.Object, error)
Use pointer if the function returning single struct 
```
CreateObject(ctx context.Context, obj entity.Object) (*entity.Object, error)
```

so in error handling you can return `nil` as first argument

```
if err != nil {
...
return nil, err
}
```

2023-10-27 04:25 UTC, johndy2742 commented on service/src/modules/object/usecase/usecase.go
> +		CreateObject(ctx context.Context, obj entity.Object) (entity.Object, error)
ok kang @alqinsidev, already refactor to use pointer

2023-10-27 04:29 UTC, iqbal167 commented on service/src/app/app.go
> +		newrelicApp *newrelic.Application
If you dont use it, please remove the new relic field

2023-10-27 04:32 UTC, iqbal167 commented on service/src/modules/object/entity/entity.go
> +package entity
Make it separate for entity and response @johndy2742

2023-10-27 04:32 UTC, johndy2742 commented on service/src/app/app.go
> +		newrelicApp *newrelic.Application
oh sorry kang @iqbal167 , it turns out it didnt get commited when i changed it

2023-10-27 06:58 UTC, alqinsidev commented
also remove all the comment, it doesn't necessary.

2023-10-27 11:53 UTC, alqinsidev requested changes

2023-10-27 11:53 UTC, alqinsidev commented on service/src/modules/object/endpoint/endpoint.go
> +		CreateObject(ctx context.Context, objData request.Object) (*response.Object, error)
referring to current pattern, endpoint function should return `interface{}` rather than struct

2023-10-27 11:53 UTC, alqinsidev commented on service/src/modules/object/transport/handler/http/response/create_object.go
> +		ID          uint64         `json:"id"`
For security reason, I prefer `UUID` type for the ID. So you can use string or the uuid type itself for the ID key.

2023-10-27 13:52 UTC, iqbal167 commented on service/src/modules/object/endpoint/create_object.go
> +	createdObj, err := e.usecase.CreateObject(ctx, objData)
please validate the `objData`, which any field need to set is required

2023-10-27 14:54 UTC, iqbal167 commented on service/src/modules/object/endpoint/create_object.go
> +	createdObj, err := e.usecase.CreateObject(ctx, objData)
You have not implemented validation here @johndy2742, before you passing `objData` to `e.usecase.CreateObject` function, you need to validate `objData` first, and if an error occurs, you must return validates result and error, for the error you can use custom error with ErrPayloadValidation from https://github.com/jabardigitalservice/event-management-system/blob/main/service/src/error/error.go import as _error

2023-10-30 01:33 UTC, iqbal167 commented on service/src/modules/object/endpoint/create_object.go
> +	if err := validate.Struct(objData); err != nil {
for our standardization, you can use package "github.com/fazpass/goliath/v3/helper/validator", see the example https://github.com/iqbal167/tahura/blob/main/src/modules/tahura/endpoint/post_ticket_scan.go

2023-10-30 04:01 UTC, johndy2742 commented on service/src/modules/object/endpoint/create_object.go
> +	if err := validate.Struct(objData); err != nil {
ok kang i will use the provided library for validation

2023-10-30 04:14 UTC, johndy2742 commented on service/src/modules/object/endpoint/create_object.go
> +	if err := validate.Struct(objData); err != nil {
i already use the lib provided kang, here is the newest commit [6a51e8b](https://github.com/jabardigitalservice/event-management-system/pull/15/commits/6a51e8b961a3a8ceb9008d91dbc373cebb1fc98a)

2023-10-30 05:49 UTC, iqbal167 commented on service/src/modules/object/endpoint/create_object.go
> +		return struct{}{}, _errors.ErrPayloadValidation
you can set `validates, _errors.ErrPayloadValidation` as a return value @johndy2742

2023-10-30 06:39 UTC, iqbal167 commented on service/src/modules/object/transport/handler/http/request/create_object.go
> +	Status string
can you explain this data type, why this status needs to be a custom data type?

2023-10-30 06:43 UTC, johndy2742 commented on service/src/modules/object/transport/handler/http/request/create_object.go
> +	Status string
because the status type in

	Object struct {
		ID          uuid.UUID
		Name        string
		Address     string
		Description string
		Banner      pq.StringArray
		Logo        string
		SocialMedia []SocialMedia
		Organizer   string
		Status      Status
		CreatedAt   time.Time
		UpdatedAt   time.Time
	}

is an ENUM type

2023-10-30 07:01 UTC, iqbal167 approved these changes

2023-10-30 07:29 UTC, alqinsidev approved these changes
LGTM!, Approve

2023-10-30 07:30 UTC, merged